import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#d8e3fb",
        "primary": "#545f73",
        "secondary-fixed-dim": "#c5d6f0",
        "tertiary-fixed-dim": "#d4cdee",
        "on-error": "#fff7f6",
        "surface-container-low": "#f0f4f7",
        "on-surface-variant": "#566166",
        "on-primary-container": "#475266",
        "surface-dim": "#cfdce3",
        "primary-dim": "#485367",
        "surface-container-lowest": "#ffffff",
        "outline": "#717c82",
        "error": "#9f403d",
        "tertiary": "#605c78",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#514d68",
        "inverse-surface": "#0b0f10",
        "error-dim": "#4e0309",
        "on-secondary-fixed": "#314055",
        "secondary-container": "#d3e4fe",
        "inverse-primary": "#dae6fe",
        "surface-container": "#e8eff3",
        "on-error-container": "#752121",
        "on-primary": "#f6f7ff",
        "on-primary-fixed-variant": "#515c70",
        "secondary-dim": "#44546a",
        "secondary": "#506076",
        "on-primary-fixed": "#354053",
        "outline-variant": "#a9b4b9",
        "on-secondary-container": "#435368",
        "on-secondary": "#f7f9ff",
        "primary-fixed": "#d8e3fb",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#5b5672",
        "surface-tint": "#545f73",
        "error-container": "#fe8983",
        "tertiary-fixed": "#e3dbfd",
        "surface-container-high": "#e1e9ee",
        "inverse-on-surface": "#9a9d9f",
        "surface-variant": "#d9e4ea",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-background": "#2a3439",
        "primary-fixed-dim": "#cad5ed",
        "on-tertiary-fixed": "#3e3a54",
        "tertiary-container": "#e3dbfd",
        "surface": "#f7f9fb",
        "on-surface": "#2a3439",
        "surface-container-highest": "#d9e4ea",
        "on-tertiary": "#fcf7ff",
        "tertiary-dim": "#54506b",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
